version: '3.8'
services:
  app:
    build: .
    ports:
      - '${PORT}:3000'
    depends_on:
      - todo-db
    env_file:
      - .env
  todo-db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
